name: Pipeline Home-Chef-Backend

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: 
        cd HOME-CHEF
        mvn clean install -DskipTests

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: jar file
        path: HOME-CHEF/target/*.jar

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: 
        cd HOME-CHEF
        mvn clean test site

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: test report
        path: HOME-CHEF/target/site/

